// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn45dyi5jad2LUI8ba3uJkmtyjeOpCp7s',
    appId: '1:903673294841:web:5a20522cb800622ecfd728',
    messagingSenderId: '903673294841',
    projectId: 'locke-d2513',
    authDomain: 'locke-d2513.firebaseapp.com',
    storageBucket: 'locke-d2513.firebasestorage.app',
    measurementId: 'G-Q0LWPBJ43G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6VnGirGN7Y2cQz6iuel6LUnYflugzsY',
    appId: '1:903673294841:android:d4f12752256d5f3dcfd728',
    messagingSenderId: '903673294841',
    projectId: 'locke-d2513',
    storageBucket: 'locke-d2513.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF_ma9LKHJarh2qoq8XSeEdMN1S_0x98k',
    appId: '1:903673294841:ios:ea3aebd20d52af87cfd728',
    messagingSenderId: '903673294841',
    projectId: 'locke-d2513',
    storageBucket: 'locke-d2513.firebasestorage.app',
    iosBundleId: 'com.example.locke',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF_ma9LKHJarh2qoq8XSeEdMN1S_0x98k',
    appId: '1:903673294841:ios:ea3aebd20d52af87cfd728',
    messagingSenderId: '903673294841',
    projectId: 'locke-d2513',
    storageBucket: 'locke-d2513.firebasestorage.app',
    iosBundleId: 'com.example.locke',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn45dyi5jad2LUI8ba3uJkmtyjeOpCp7s',
    appId: '1:903673294841:web:a746d57a007b829fcfd728',
    messagingSenderId: '903673294841',
    projectId: 'locke-d2513',
    authDomain: 'locke-d2513.firebaseapp.com',
    storageBucket: 'locke-d2513.firebasestorage.app',
    measurementId: 'G-E19VQXR37S',
  );
}
